apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/kyriosproj/kyrios/kube/app-templates/base
commonLabels:
  app: example-golang
patches:
- target:
    name: APP_NAME
  path: patch_names.yaml # Patch all resource names
